log.txt

Describe progress, meeting minutes, and summaries

log.txt file

---

.gitignore
backend/.gitignore
backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/repositories/StudyAreaRepository.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java

Backend for study area model. Commit includes: creating Study Area Model, StudyAreaController, StudyAreaRequest, StudyAreaRepository with 5 study area locations in the Database.

Display study area amenities

---

.vscode/extensions.json
.vscode/launch.json
backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java

Can u guys check over my work/Test it?

Added the getBusiness() method to the StudyAreas Class

---

frontend/src/app/app.component.css
frontend/src/app/app.component.html
frontend/src/app/app.component.ts
frontend/src/app/map/map.component.css
frontend/src/app/study-area/study-area.component.css
frontend/src/app/study-area/study-area.component.html
frontend/src/app/study-area/study-area.component.spec.ts
frontend/src/app/study-area/study-area.component.ts

added the frontend for study areas to display the study areas and its amenities. the commit will include study-area.component.css, study-area.component.html, study-area.component.spec.ts, and study-area.component.ts

Display Study Areas and its amenities

---

frontend/angular.json
frontend/src/app/study-area/study-area.component.css

Corrected clicking on the map with assistance from <a href="https://github.com/Jimmykhangnguyen" target="_blank">Jimmykhangnguyen</a>

Fixed offset issue

---

frontend/src/app/map/map.component.css
frontend/src/app/study-area/study-area.component.css
frontend/src/app/study-area/study-area.component.html
frontend/src/app/study-area/study-area.component.ts

Basically provided some improvements to the UI we had before, adding some buttons and animations.

Revamped the front-end for study places and amenities

---

backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/test/java/com/backend/database/models/StudyAreaTest.java
frontend/package-lock.json
frontend/package.json

Added study area model jUnit test class. Modified the model class to fix range issues for cleanliness rating and loudness.

Added study area model JUnit test class.

---

frontend/src/app/map/map.component.html
frontend/src/app/map/map.component.ts
frontend/src/app/study-area/study-area.component.ts
frontend/src/app/study-map-service/study-map-service.ts
log.txt

Added directions from a selectable starting point to a selected study area

Implemented proper directions

---

backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java

Used arraylists for now, if it doesn't work with the database we can change it.

Added a method for text ratings

---

frontend/package-lock.json
frontend/package.json
frontend/src/app/study-area/study-area.component.html
frontend/src/app/study-area/study-area.component.ts

Built a basic filtering function for the app

Filter backend

---

frontend/src/app/map/map.component.ts
frontend/src/app/study-area/study-area.component.html
frontend/src/app/study-area/study-area.component.ts

Aligned stub database format with real database format, may work

Proper directions changes

---

backend/pom.xml
backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java
backend/src/test/java/com/backend/database/models/StudyAreaTest.java
frontend/src/app/study-area/study-area.component.ts

This Pull Request adds the backend for the rating system as well as API endpoints to get and modify each study areas' ratings.

Added the backend for the rating system

---

frontend/src/app/app.component.html
frontend/src/app/app.component.ts
frontend/src/app/map/map.component.css
frontend/src/app/nav-bar/nav-bar.component.css
frontend/src/app/nav-bar/nav-bar.component.html
frontend/src/app/nav-bar/nav-bar.component.spec.ts
frontend/src/app/nav-bar/nav-bar.component.ts
frontend/src/app/study-area/study-area.component.css
frontend/src/app/study-area/study-area.component.ts

Removed old study area UI code

Nav bar development

---

frontend/src/app/nav-bar/nav-bar.component.css
frontend/src/app/nav-bar/nav-bar.component.html

Fixed the Nav Bar's front end so the text is center height-wise

---

backend/src/main/java/com/backend/database/models/User.java

Added a User model in preparation for user authentication

Added a User model in preparation for user authentication

---

frontend/src/app/app.routes.ts
frontend/src/app/nav-bar/nav-bar.component.css
frontend/src/app/nav-bar/nav-bar.component.html
frontend/src/app/nav-bar/nav-bar.component.ts

Fixed the nav bar so it looks similar to Ashley's mockups!
Check out the demo video I sent on the group chat!

Fix nav bar

---

.vscode/settings.json
backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java

Ratings Back End constructors and stuff

---

backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java

What the title says - please review.

Fixed Busyness Spelling Issue

---

backend/src/main/java/com/backend/database/controllers/UserController.java
frontend/src/app/app.component.ts
frontend/src/app/app.routes.ts
frontend/src/app/login/login.component.html
frontend/src/app/login/login.component.ts
frontend/src/app/register/register.component.css
frontend/src/app/register/register.component.html
frontend/src/app/register/register.component.spec.ts
frontend/src/app/register/register.component.ts

Added the register component, that will register a user and check if that email is unique (not already in database) and that the email and password follow a specific format. Password should be of length 8-20, include at least 1 uppercase and 1 number. Email should not already be registered and have @ and either com or ca in the email. Also, i added a "re-enter" password section to verify the password. Modified the app.routes.ts as well to route to correct login or register page.

Register component

---

backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/controllers/UserController.java
backend/src/main/java/com/backend/database/resources/UserRequest.java

Reverts Jimmykhangnguyen/StudyWith-York-U#74

Revert "User Request for Favourites array"

---

frontend/src/app/study-area/study-area.component.ts

Issue with data stored in database

Fixed swapped lat long

---

log.txt

Based on pr's, I'd advise it to be looked over

Log update up to March 23

---

frontend/src/app/favourites/favourites.component.ts
frontend/src/app/study-area/study-area.component.ts

Quick fix for the stub database

Stub study areas fix

---

frontend/src/app/favourites/favourites.component.html

Minimal visual update

---

frontend/src/app/map/map.component.ts
frontend/src/app/study-map-service/study-map-service.ts

Each rating now updates when they're submitted

Live update each rating

---

frontend/src/app/study-area/study-area.component.css

Minor address fix

---

frontend/src/app/register/register.component.html

Hides the re-enter password field like the password field

Hid password confirmation

---

frontend/src/app/stub-database/stub-database.ts
frontend/src/app/study-area/study-area.component.html
frontend/src/app/study-area/study-area.component.ts

Didn't get committed from a previous branch

Filter fix

---

backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java
backend/src/test/java/com/backend/database/models/StudyAreaTest.java

Backend work, doesn't affect frontend

Removed dead counts

---

backend/src/main/java/com/backend/database/controllers/StudyAreaController.java
backend/src/main/java/com/backend/database/models/StudyArea.java
backend/src/main/java/com/backend/database/resources/StudyAreaRequest.java
backend/src/test/java/com/backend/database/models/StudyAreaTest.java
frontend/src/app/favourites/favourites.component.css
frontend/src/app/favourites/favourites.component.html
frontend/src/app/study-area/study-area.component.css

The visual of favourites used for deliverable 2

Presented favourites
